export type Ingredient = {
  id: number;
  label: string;
  color: string;
  categoryId: number;
};

export type Category = {
  id: number;
  label: string;
};

export const ingredients: Ingredient[] = [
  {
    id: 1,
    label: "Mushroom",
    color: "#5D6D7E",
    categoryId: 1,
  },
  {
    id: 2,
    label: "Onion",
    color: "#F1C40F",
    categoryId: 1,
  },
  {
    id: 3,
    label: "Bell Pepper",
    color: "#E74C3C",
    categoryId: 1,
  },
  {
    id: 4,
    label: "Olives",
    color: "#D35400",
    categoryId: 1,
  },
  {
    id: 5,
    label: "Tomato",
    color: "#F5B041",
    categoryId: 1,
  },
  {
    id: 6,
    label: "Spinach",
    color: "#F7DC6F",
    categoryId: 1,
  },
  {
    id: 7,
    label: "Basil",
    color: "#95A5A6",
    categoryId: 1,
  },
  {
    id: 8,
    label: "Jalapeno",
    color: "#7F8C8D",
    categoryId: 1,
  },
  {
    id: 9,
    label: "Artichoke",
    color: "#2E86C1",
    categoryId: 1,
  },
  {
    id: 10,
    label: "Pesto",
    color: "#138D75",
    categoryId: 1,
  },
  {
    id: 11,
    label: "Balsamic Vinegar",
    color: "#C0392B",
    categoryId: 1,
  },
  {
    id: 12,
    label: "Ricotta Cheese",
    color: "#FF5733",
    categoryId: 1,
  },
  {
    id: 13,
    label: "Mozzarella Cheese",
    color: "#E67E22",
    categoryId: 1,
  },
  {
    id: 14,
    label: "Parmesan Cheese",
    color: "#F1C40F",
    categoryId: 1,
  },
  {
    id: 15,
    label: "Feta Cheese",
    color: "#7F8C8D",
    categoryId: 1,
  },
  {
    id: 16,
    label: "Gorgonzola Cheese",
    color: "#5D6D7E",
    categoryId: 1,
  },
  {
    id: 17,
    label: "Pepperoni",
    color: "#F5B041",
    categoryId: 2,
  },
  {
    id: 18,
    label: "Sausage",
    color: "#F7DC6F",
    categoryId: 2,
  },
  {
    id: 19,
    label: "Ham",
    color: "#95A5A6",
    categoryId: 2,
  },
  {
    id: 20,
    label: "Bacon",
    color: "#7F8C8D",
    categoryId: 2,
  },
  {
    id: 21,
    label: "Chicken",
    color: "#5D6D7E",
    categoryId: 2,
  },
  {
    id: 22,
    label: "Beef",
    color: "#F1C40F",
    categoryId: 2,
  },
  {
    id: 23,
    label: "Salami",
    color: "#E74C3C",
    categoryId: 2,
  },
  {
    id: 24,
    label: "Prosciutto",
    color: "#D35400",
    categoryId: 2,
  },
  {
    id: 25,
    label: "Ground Beef",
    color: "#F5B041",
    categoryId: 2,
  },
  {
    id: 26,
    label: "Ground Pork",
    color: "#F7DC6F",
    categoryId: 2,
  },
  {
    id: 27,
    label: "Ground Turkey",
    color: "#95A5A6",
    categoryId: 2,
  },
  {
    id: 28,
    label: "Anchovy",
    color: "#7F8C8D",
    categoryId: 2,
  },
  {
    id: 29,
    label: "Tuna",
    color: "#5D6D7E",
    categoryId: 2,
  },
  {
    id: 30,
    label: "Shrimp",
    color: "#F1C40F",
    categoryId: 2,
  },
  {
    id: 31,
    label: "Crab",
    color: "#E74C3C",
    categoryId: 2,
  },
  {
    id: 32,
    label: "Lobster",
    color: "#D35400",
    categoryId: 2,
  },
  {
    id: 33,
    label: "Scallops",
    color: "#F5B041",
    categoryId: 2,
  },
  {
    id: 34,
    label: "Clams",
    color: "#F7DC6F",
    categoryId: 2,
  },
  {
    id: 35,
    label: "Mussels",
    color: "#95A5A6",
    categoryId: 2,
  },
  {
    id: 36,
    label: "Oysters",
    color: "#7F8C8D",
    categoryId: 2,
  },
  {
    id: 37,
    label: "Red Sauce",
    color: "#5D6D7E",
    categoryId: 3,
  },
  {
    id: 38,
    label: "Marinara Sauce",
    color: "#F1C40F",
    categoryId: 3,
  },
  {
    id: 39,
    label: "Alfredo Sauce",
    color: "#E74C3C",
    categoryId: 3,
  },
  {
    id: 40,
    label: "Barbecue Sauce",
    color: "#D35400",
    categoryId: 3,
  },
  {
    id: 41,
    label: "Pesto Sauce",
    color: "#F5B041",
    categoryId: 3,
  },
  {
    id: 42,
    label: "Garlic Sauce",
    color: "#F7DC6F",
    categoryId: 3,
  },
  {
    id: 43,
    label: "White Sauce",
    color: "#95A5A6",
    categoryId: 3,
  },
  {
    id: 44,
    label: "Herb Sauce",
    color: "#7F8C8D",
    categoryId: 3,
  },
  {
    id: 45,
    label: "Tomato Sauce",
    color: "#5D6D7E",
    categoryId: 3,
  },
  {
    id: 46,
    label: "Cheese Sauce",
    color: "#F1C40F",
    categoryId: 3,
  },
  {
    id: 47,
    label: "Olive Oil",
    color: "#E74C3C",
    categoryId: 4,
  },
  {
    id: 48,
    label: "Balsamic Vinegar",
    color: "#D35400",
    categoryId: 4,
  },
  {
    id: 49,
    label: "Parmesan Cheese",
    color: "#F5B041",
    categoryId: 4,
  },
  {
    id: 50,
    label: "Garlic",
    color: "#F7DC6F",
    categoryId: 4,
  },
  {
    id: 51,
    label: "Oregano",
    color: "#5A51A6",
    categoryId: 4,
  },
  {
    id: 52,
    label: "Basil",
    color: "#7F8C8D",
    categoryId: 4,
  },
  {
    id: 53,
    label: "Rosemary",
    color: "#5D6D7E",
    categoryId: 4,
  },
  {
    id: 54,
    label: "Thyme",
    color: "#F1C40F",
    categoryId: 4,
  },
  {
    id: 55,
    label: "Paprika",
    color: "#E74C3C",
    categoryId: 4,
  },
  {
    id: 56,
    label: "Cumin",
    color: "#D35400",
    categoryId: 4,
  },
  {
    id: 57,
    label: "Coriander",
    color: "#F5B041",
    categoryId: 4,
  },
  {
    id: 58,
    label: "Cayenne Pepper",
    color: "#F7DC6F",
    categoryId: 4,
  },
  {
    id: 59,
    label: "Black Pepper",
    color: "#95A5A6",
    categoryId: 4,
  },
  {
    id: 60,
    label: "Red Pepper Flakes",
    color: "#7F8C8D",
    categoryId: 4,
  },
  {
    id: 61,
    label: "Chili Powder",
    color: "#5D6D7E",
    categoryId: 4,
  },
  {
    id: 62,
    label: "Garlic Powder",
    color: "#F1C40F",
    categoryId: 4,
  },
  {
    id: 63,
    label: "Onion Powder",
    color: "#E74C3C",
    categoryId: 4,
  },
  {
    id: 64,
    label: "Mustard Powder",
    color: "#D35400",
    categoryId: 4,
  },
  {
    id: 65,
    label: "Cinnamon",
    color: "#F5B041",
    categoryId: 4,
  },
  {
    id: 66,
    label: "Nutmeg",
    color: "#F7DC6F",
    categoryId: 4,
  },
  {
    id: 67,
    label: "Vanilla",
    color: "#95A5A6",
    categoryId: 4,
  },
  {
    id: 68,
    label: "Lemon Juice",
    color: "#7F8C8D",
    categoryId: 4,
  },
  {
    id: 69,
    label: "Lime Juice",
    color: "#5D6D7E",
    categoryId: 4,
  },
  {
    id: 70,
    label: "Orange Juice",
    color: "#F1C40F",
    categoryId: 4,
  },
  {
    id: 71,
    label: "Honey",
    color: "#E74C3C",
    categoryId: 4,
  },
  {
    id: 72,
    label: "Maple Syrup",
    color: "#D35400",
    categoryId: 4,
  },
  {
    id: 73,
    label: "Hot Sauce",
    color: "#F5B041",
    categoryId: 4,
  },
  {
    id: 74,
    label: "Soy Sauce",
    color: "#F7DC6F",
    categoryId: 4,
  },
  {
    id: 75,
    label: "Worcestershire Sauce",
    color: "#95A5A6",
    categoryId: 4,
  },
  {
    id: 76,
    label: "Mustard",
    color: "#7F8C8D",
    categoryId: 4,
  },
  {
    id: 77,
    label: "Barbecue Sauce",
    color: "#5D6D7E",
    categoryId: 4,
  },
  {
    id: 78,
    label: "Ranch Dressing",
    color: "#F1C40F",
    categoryId: 4,
  },
  {
    id: 79,
    label: "Blue Cheese Dressing",
    color: "#E74C3C",
    categoryId: 4,
  },
  {
    id: 80,
    label: "Italian Dressing",
    color: "#D35400",
    categoryId: 4,
  },
  {
    id: 81,
    label: "Vinaigrette",
    color: "#F5B041",
    categoryId: 4,
  },
  {
    id: 82,
    label: "Thousand Island Dressing",
    color: "#F7DC6F",
    categoryId: 4,
  },
  {
    id: 83,
    label: "Honey Mustard Dressing",
    color: "#95A5A6",
    categoryId: 4,
  },
  {
    id: 84,
    label: "Caesar Dressing",
    color: "#7F8C8D",
    categoryId: 4,
  },
  {
    id: 85,
    label: "French Dressing",
    color: "#5D6D7E",
    categoryId: 4,
  },
  {
    id: 86,
    label: "Balsamic Vinaigrette",
    color: "#F1C40F",
    categoryId: 4,
  },
  {
    id: 87,
    label: "Green Onion",
    color: "#E74C3C",
    categoryId: 1,
  },
  {
    id: 88,
    label: "Arugula",
    color: "#D35400",
    categoryId: 1,
  },
  {
    id: 89,
    label: "Pepperoncini",
    color: "#F5B041",
    categoryId: 1,
  },
  {
    id: 90,
    label: "Sun-Dried Tomatoes",
    color: "#F7DC6F",
    categoryId: 1,
  },
  {
    id: 91,
    label: "Roasted Red Peppers",
    color: "#95A5A6",
    categoryId: 1,
  },
  {
    id: 92,
    label: "Pineapple",
    color: "#7F8C8D",
    categoryId: 1,
  },
  {
    id: 93,
    label: "Peaches",
    color: "#5D6D7E",
    categoryId: 1,
  },
  {
    id: 94,
    label: "Mango",
    color: "#F1C40F",
    categoryId: 1,
  },
  {
    id: 95,
    label: "Banana Peppers",
    color: "#E74C3C",
    categoryId: 1,
  },
  {
    id: 96,
    label: "Caramelized Onions",
    color: "#D35400",
    categoryId: 1,
  },
  {
    id: 97,
    label: "Roasted Garlic",
    color: "#F5B041",
    categoryId: 1,
  },
  {
    id: 98,
    label: "Grilled Zucchini",
    color: "#F7DC6F",
    categoryId: 1,
  },
  {
    id: 99,
    label: "Roasted Eggplant",
    color: "#95A5A6",
    categoryId: 1,
  },
  {
    id: 100,
    label: "Roasted Butternut Squash",
    color: "#7F8C8D",
    categoryId: 1,
  },

  {
    id: 101,
    label: "Alfredo Sauce",
    color: "#6D214F",
    categoryId: 3,
  },
  {
    id: 102,
    label: "Marinara Sauce",
    color: "#214F6D",
    categoryId: 3,
  },
  {
    id: 103,
    label: "Barbecue Sauce",
    color: "#4F6D21",
    categoryId: 3,
  },
  {
    id: 104,
    label: "Hot Sauce",
    color: "#6D4F21",
    categoryId: 3,
  },
  {
    id: 105,
    label: "Soy Sauce",
    color: "#21436D",
    categoryId: 3,
  },
  {
    id: 106,
    label: "Honey Mustard Sauce",
    color: "#4F216D",
    categoryId: 3,
  },
  {
    id: 36,
    label: "Ranch Dressing",
    color: "#6D2146",
    categoryId: 3,
  },
  {
    id: 107,
    label: "Thousand Island Dressing",
    color: "#216D4F",
    categoryId: 3,
  },
];

export const categories: Category[] = [
  {
    id: 1,
    label: "Veggies",
  },
  {
    id: 2,
    label: "Meats",
  },
  {
    id: 3,
    label: "Sauces",
  },
  {
    id: 4,
    label: "Herbs and Spices",
  },
];
